### PR TITLE
build fix and build settings

### LINKED ISSUE #115: make first test build, to check if the game builds at all, resolve problems if not

### PR DESCRIPTION
**Pull request by ZieIony**

### CODE REVIEW

File: Assets/Scripts/EnemyUI.cs [hunk 1]
```diff
@@ -56,6 +56,6 @@ void Update()
         if (agitationController.AgitationState == AgitationState.Alarmed) color = Color.red;
 
         float alpha = agitationController.AgitationLevel / 100;
-        label.style.color = new StyleColor(color.WithAlpha(alpha));
```
Comment (ZieIony) [inline Assets/Scripts/EnemyUI.cs:59]: This is the fix. For some reason the Unity build tool cannot find the required method. Maybe because it's an extension?

**Comment by ZieIony** [comment]
feel free to merge this without me
